#!/usr/bin/env python

import rospy, time

from linedetector import LineDetector
from obstacledetector import ObstacleDetector
from motordriver import MotorDriver

class AutoDrive:
    def __init__(self):
        rospy.init_node('xycar_driver')
        self.line_detector = LineDetector('/usb_cam/image_raw')
        self.obstacle_detector = ObstacleDetector('/ultrasonic')
        self.driver = MotorDriver('/xycar_motor_msg')
	self.a = 0
    def trace(self):
        obs_l, obs_m, obs_r = self.obstacle_detector.get_distance()
        line_r = self.line_detector.detect_lines()
        #self.line_detector.show_images(line_r)
        angle = self.steer(line_r)
        speed = self.accelerate(angle, obs_l, obs_m, obs_r)
        self.driver.drive(angle + 90, speed + 90)
    
    def steer(self, right):
	angle = 0
	if right<0:
	    angle = self.a
        elif right <= 557:
            angle = -40
	#elif right <= 460:
	   # angle = -30
	#elif 0 <= left <= 10 :
	 #   angle = -20
	#elif 120 <= left <= 160:
	#    angle = 20 
	#elif right > 520:
            #angle = 40
	elif right >600:
	    angle = 40
	print(right)
	self.a = angle
	return angle

    def accelerate(self, angle, left, mid, right):
        if min(left, mid, right) < 50:
            speed = 10
        elif angle < -20 or angle > 20:
            speed = 10
        else:
            speed = 20
        return 20
    def exit(self):
        print('finished')

if __name__ == '__main__':
    car = AutoDrive()
    time.sleep(3)
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        car.trace()
        rate.sleep()
    rospy.on_shutdown(car.exit)
